version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=ms
     - MYSQL_USER=ons
     - MYSQL_PASSWORD=1234
    volumes:
     - achatdb:/var/lib/mysql

  spring_app:
    image: onschebbi/chebbims:latest
    container_name: backcontainer
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/ms?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
     - 8090:8090
    depends_on:
     - mysqldb

volumes:
  ms: