version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=ms
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
    volumes:
     - ms:/var/lib/mysql

  spring_app:
    image: onschebbi/chebbi:latest
    container_name: backcontainer1
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/ms?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
     - 8089:8089
    depends_on:
     - mysqldb

volumes:
  ms: